version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn --bind 0.0.0.0:8000 arbat.wsgi:application
    volumes:
      - ./src:/app
      - ./src/staticfiles:/app/staticfiles
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=arbat.settings


# Удалены секции для db и nginx
