# Generated by Django 5.1.4 on 2024-12-24 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True, verbose_name="Дата рождения"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="photo",
            field=models.ImageField(
                blank=True, upload_to="user_photos/", verbose_name="Фотография"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(
                max_length=25, unique=True, verbose_name="Номер телефона"
            ),
        ),
    ]
