# Generated by Django 5.1.4 on 2024-12-24 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_customuser_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("admin", "Администратор"),
                    ("manager", "Менеджер"),
                    ("user", "Пользователь"),
                ],
                max_length=255,
            ),
        ),
    ]
