# Generated by Django 5.1.4 on 2024-12-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_customuser_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[("rieltor", "Риелтор"), ("manager", "Менеджер")],
                default="rieltor",
                max_length=255,
            ),
        ),
    ]
