# Generated by Django 5.1.4 on 2025-01-01 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_customuser_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[("realtor", "Риелтор"), ("manager", "Менеджер")],
                default="realtor",
                max_length=255,
            ),
        ),
    ]
