# Generated by Django 5.1.4 on 2025-01-01 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0002_rename_realtor_mortgageapplication_rieltor"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mortgageapplication",
            old_name="rieltor",
            new_name="realtor",
        ),
    ]
