# Generated by Django 5.1.4 on 2025-01-01 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0003_rename_rieltor_mortgageapplication_realtor"),
    ]

    operations = [
        migrations.AddField(
            model_name="mortgageapplication",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("in_work", "В работе"),
                    ("first_approved", "Первоначальное одобрение"),
                    ("approved", "Одобрено"),
                    ("rejected", "Не одобрено"),
                ],
                default="in_work",
                max_length=50,
            ),
        ),
    ]
