# Generated by Django 5.1.4 on 2025-01-01 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0004_mortgageapplication_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mortgageapplication",
            options={
                "verbose_name": "Заявка на ипотеку",
                "verbose_name_plural": "Заявки на ипотеку",
            },
        ),
        migrations.AddField(
            model_name="mortgageapplication",
            name="iin",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
