# Generated by Django 5.1.4 on 2025-01-03 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0007_mortgageapplication_manager_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mortgageapplication",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="Сумма ипотеки"
            ),
        ),
        migrations.AlterField(
            model_name="mortgageapplication",
            name="city",
            field=models.CharField(max_length=100, verbose_name="Город"),
        ),
        migrations.AlterField(
            model_name="mortgageapplication",
            name="code",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Код заявки"
            ),
        ),
        migrations.AlterField(
            model_name="mortgageapplication",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
        ),
        migrations.AlterField(
            model_name="mortgageapplication",
            name="down_payment",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="Первоначальный взнос"
            ),
        ),
        migrations.AlterField(
            model_name="mortgageapplication",
            name="full_name",
            field=models.CharField(max_length=255, verbose_name="ФИО"),
        ),
        migrations.AlterField(
            model_name="mortgageapplication",
            name="mortgage_term",
            field=models.IntegerField(verbose_name="Срок ипотеки"),
        ),
        migrations.AlterField(
            model_name="mortgageapplication",
            name="phone_number",
            field=models.CharField(max_length=25, verbose_name="Номер телефона"),
        ),
        migrations.AlterField(
            model_name="mortgageapplication",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("in_work", "В работе"),
                    ("first_approved", "Первоначальное одобрение"),
                    ("approved", "Одобрено"),
                    ("rejected", "Не одобрено"),
                ],
                default="in_work",
                max_length=50,
                verbose_name="Статус",
            ),
        ),
    ]
