# Generated by Django 5.1.4 on 2025-02-01 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0008_alter_mortgageapplication_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mortgageapplication",
            name="code_requested",
            field=models.BooleanField(default=False, verbose_name="Код запрошен"),
        ),
    ]
